# Generated by Django 5.1.1 on 2024-10-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_tasks_profile_tasks_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='id',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
