# Generated by Django 5.1.1 on 2024-10-22 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_tasks_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='id',
        ),
    ]
